name: daily_work
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+101

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl:
  fl_chart: ^1.1.1
  persian_datetime_picker: ^3.2.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  archive: ^4.0.7
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    - assets/fonts/ # اگر پوشه assets دارید، فونت را در اینجا قرار دهید
  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/sans.ttf
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir.ttf
    - family: yekan
      fonts:
        - asset: assets/fonts/yekan.ttf
    - family: koodak
      fonts:
        - asset: assets/fonts/koodak.ttf
